### ISSUE TITLE
Sync filter manager Error when applying filter to a user

### ISSUE THREAD

**Issue by yilmaz1976** [MscrmTools/MscrmTools.SyncFilterManager#3]
Hi

I get an error when I use the function "Apply to User" from the Synchronization Filters Templates. 
When I pick 4 templates on the outlook "Filters Templates" and apply for a user, I get the error "Error while applying filters to users: Cannot assign outlook filters". But when I load the "Users Synchronization filters" only one filter is applyed. It seems that it is only able possible to copy one filter template at time. Its a tough work to copy for many users with one filter at time :o). Is that some thing that will be fixed, or have missed some thing during my copying?
![2018-06-05_16-01-18_1](https://user-images.githubusercontent.com/4425618/40981652-fe62a7de-68ca-11e8-8e95-33c6a2c7188c.png)
![2018-06-05_16-01-18_2](https://user-images.githubusercontent.com/4425618/40981654-feccfa9e-68ca-11e8-9111-b30013838b8c.png)

**Comment by MscrmTools** [comment]
The error message is a standard one from CRM platform. It does apply only one since when it fails, it stops processing. So I guess it fails on the second item to apply

**Comment by yilmaz1976** [comment]
Wil there ve a fix om this?

**Comment by MscrmTools** [comment]
It would need to understand first why a filter cannot be applied. 
So I’m not sure yet if there is a possible fix

**Comment by jlearned023** [comment]
This happened to me.  What I did to fix was to manually go to the user's computer and add it. However, when I went to add the filter manually I noticed that it already existed and was enabled.  So I re-enabled the filter to be sure and then it worked.  I believe there was something getting crossed that was showing FilterManager the filter didn't exist but when it tried to add it, it threw an error saying it couldn't be added (probably because it told the system that it did exist and didn't want to duplicate).  Anyways, work around for me was to re-enable the filter manually

**Comment by jellevervloessem** [comment]
When you first remove the filter for the user, and then reapply the new template to a user, it will be recreated.
So I think the error-message sais that it cannot changa an existing filter. 

For me it worked by deleting first.

**Comment by MscrmTools** [comment]
ok, so the fix would be to delete template applied to user before being able to apply another one? I will test this behavior

**Comment by MscrmTools** [comment]
Should be fixed with fix of #2 
New release on its way.
